/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./main.js",
    "./*.js"
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0053a6",
        "on-primary-container": "#ebf0ff",
        "secondary-fixed": "#d5e3ff",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#aac7ff",
        "primary-container": "#006bd3",
        "outline": "#727784",
        "on-primary-fixed": "#001b3e",
        "tertiary-fixed-dim": "#6fd7d0",
        "secondary": "#3a5f94",
        "on-secondary-fixed-variant": "#1f477b",
        "surface-variant": "#e2e2e3",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#00504c",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#8cf4ec",
        "on-secondary-fixed": "#001b3c",
        "on-surface": "#1a1c1d",
        "inverse-primary": "#aac7ff",
        "primary-fixed": "#d6e3ff",
        "on-primary-fixed-variant": "#00458d",
        "on-tertiary-fixed": "#00201e",
        "error": "#ba1a1a",
        "surface-container": "#edeeef",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f4f4",
        "surface": "#f9f9fa",
        "surface-container-highest": "#e2e2e3",
        "background": "#f9f9fa",
        "tertiary-container": "#007a75",
        "surface-tint": "#005db8",
        "on-secondary-container": "#294f83",
        "inverse-surface": "#2e3132",
        "secondary-fixed-dim": "#a7c8ff",
        "secondary-container": "#9fc2fe",
        "on-background": "#1a1c1d",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9fa",
        "on-tertiary-container": "#aafff8",
        "on-surface-variant": "#414753",
        "outline-variant": "#c1c6d5",
        "tertiary": "#005f5b",
        "on-error-container": "#93000a"
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
